version: '3'
services:
  node-api:
    image: node:14.18-alpine3.12
    container_name: clean-node-api
    working_dir: /usr/app/clean-node-api
    command: npm run debug
    restart: always
    ports:
      - 5050:5050
      - 9222:9222
    volumes:
      - .:/usr/app/clean-node-api
    links:
      - mongo
  
  mongo:
    image: mongo:4.4.6
    container_name: mongo-clean-node-api
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./.volumes/mongo:/data/db

